{"traceId":"4c403859e50a70f6a396fa151f3d60b3","displayName":"menuSuggestionFlow","startTime":1761089145024,"endTime":1761089145029.4707,"spans":{"b2d8eb5fd26456a9":{"spanId":"b2d8eb5fd26456a9","traceId":"4c403859e50a70f6a396fa151f3d60b3","startTime":1761089145024,"endTime":1761089145029.4707,"attributes":{"genkit:type":"action","genkit:metadata:subtype":"flow","genkit:name":"menuSuggestionFlow","genkit:isRoot":true,"genkit:path":"/{menuSuggestionFlow,t:flow}","genkit:input":"\"bbq\"","genkit:state":"error","genkit:isFailureSource":true},"displayName":"menuSuggestionFlow","links":[],"instrumentationLibrary":{"name":"genkit-tracer","version":"v1"},"spanKind":"INTERNAL","sameProcessAsParentSpan":{"value":true},"status":{"code":2,"message":"INVALID_ARGUMENT: Must supply a `model` to `generate()` calls."},"timeEvents":{"timeEvent":[{"time":1761089145029.1409,"annotation":{"attributes":{"exception.type":"400","exception.message":"INVALID_ARGUMENT: Must supply a `model` to `generate()` calls.","exception.stacktrace":"GenkitError: INVALID_ARGUMENT: Must supply a `model` to `generate()` calls.\n    at resolveModel (C:\\Users\\boshr\\StudioProjects\\xenodate\\functions\\node_modules\\@genkit-ai\\ai\\src\\model.ts:511:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async toGenerateActionOptions (C:\\Users\\boshr\\StudioProjects\\xenodate\\functions\\node_modules\\@genkit-ai\\ai\\src\\generate.ts:497:25)\n    at async generate (C:\\Users\\boshr\\StudioProjects\\xenodate\\functions\\node_modules\\@genkit-ai\\ai\\src\\generate.ts:391:18)"},"description":"exception"}}]}}}}